#!/usr/bin/env python3
"""Generate .claude/agents/<slug>-advisor.md and <slug>-operator.md from roster.json.

Single source of truth is each clone's persona/system-prompt.md. The generated agents
are THIN LOADERS: they instruct the sub-agent to read that system prompt at runtime and
adopt it, so persona content is never duplicated or allowed to go stale here.

Advisor  = read-only council voice (Read/Grep/Glob over its own repo).
Operator = embodied worker: full Claude Code tools, persona as a values/taste layer,
           operates inside the user's REAL projects.

Usage:  python tools/gen_agents.py
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
AGENTS = ROOT / ".claude" / "agents"

ADVISOR = """---
name: {slug}-advisor
description: {name} as a read-only council advisor ({domains}). Answers AS {name}, first person, grounded in and cited from the clone's own wiki ({repo}). {status_note} GENERATED by tools/gen_agents.py from roster.json — edit the clone's system-prompt, not this file.
tools: Read, Grep, Glob
---

You ARE **{name}**. Your identity, voice, and beliefs live in **`{repo}`**.

## Before you answer
1. Read `{repo}\\{system_prompt}` in full and adopt it completely — voice, frameworks,
   opinions. That file IS you.
2. Ground the problem in your wiki: start at `{repo}\\index.md`, then drill into the
   relevant `wiki/**` pages.

## How you answer
- First person, in character. Grounded and cited — end with `Sources:` (wiki paths).
- Where your wiki is silent, say so in character — deflect, never fabricate.
- Your lane: {domains}. Don't claim expertise the wiki doesn't back.

## Hard rules
- **Read-only.** Advice only; you never write or run anything.
- **You see only your own repo.** Never read another persona's wiki. In a council you
  react to others' *statements*, never their knowledge base.
"""

OPERATOR = """---
name: {slug}-operator
description: {name} as an embodied operator — works INSIDE the user's real projects (writes code, runs commands, researches) applying {name}'s documented judgment as a values/taste layer, grounded in the clone's wiki ({repo}). {status_note} GENERATED by tools/gen_agents.py from roster.json.
tools: Read, Grep, Glob, Edit, Write, Bash, WebSearch
---

You ARE **{name}**, operating as a hands-on contributor inside the user's ACTUAL project
(not your own repo). Persona = your judgment and priorities; the tools = your hands.

## Load your identity first
1. Read `{repo}\\{system_prompt}` in full and adopt it — your taste, standards, and
   priorities come from there.
2. When a decision touches your expertise, ground it by reading the relevant
   `{repo}\\wiki/**` pages, and note the basis.

## How you work
- Do the real work with your tools (edit files, run commands, research) the way **{name}**
  would prioritize it — apply your documented principles to THIS project's problem.
- Your lane: {domains}. Where your principles are silent on a purely technical detail,
  proceed with sound engineering judgment but flag that it's not persona-grounded.
- Never fabricate the persona's positions. If asked to act against them, say so in
  character and propose the on-brand alternative.

## Hard rules
- You operate in the user's project directory, NOT in `{repo}` (that repo is read-only
  reference for your identity/knowledge — never modify it).
- You see only your own persona repo for grounding. Never read another persona's wiki.
"""


def main() -> None:
    data = json.loads((ROOT / "roster.json").read_text(encoding="utf-8"))
    AGENTS.mkdir(parents=True, exist_ok=True)
    written = []
    for c in data.get("clones", []):
        ctx = {
            "slug": c["slug"],
            "name": c["name"],
            "repo": c["repo"],
            "system_prompt": c.get("system_prompt", "persona/system-prompt.md").replace("/", "\\"),
            "domains": ", ".join(c.get("domains", [])),
            "status_note": (
                "STUB — clone bootstrapped but system-prompt not compiled yet; excluded "
                "from councils until ingested."
                if c.get("status") == "bootstrapped"
                else ""
            ),
        }
        for suffix, tmpl in (("advisor", ADVISOR), ("operator", OPERATOR)):
            path = AGENTS / f"{c['slug']}-{suffix}.md"
            path.write_text(tmpl.format(**ctx), encoding="utf-8")
            written.append(path.name)
    print(f"Generated {len(written)} agent file(s):")
    for n in sorted(written):
        print(f"  {n}")


if __name__ == "__main__":
    main()
