#!/usr/bin/env python3
"""Install the roster's agent OS user-globally (~/.claude) so /work, /council etc.
work from ANY project — youtube-engine, client repos, wherever you are.

Same philosophy as gen_agents.py: the roster repo stays the single source of truth;
what lands in ~/.claude is a thin, machine-local BUILD ARTIFACT (absolute local paths),
regenerated per machine. Safe by design: only files carrying our GENERATED marker are
ever overwritten or removed; foreign files are skipped with a warning.

Usage:
  python tools/install_global.py              # install/refresh agents + command shims
  python tools/install_global.py --uninstall  # remove everything we installed
"""
import argparse
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import gen_agents  # noqa: E402

ROOT = gen_agents.ROOT
CLAUDE_DIR = pathlib.Path.home() / ".claude"
MARKER = "<!-- GENERATED by persona-roster/tools/install_global.py — edit the roster repo, then reinstall -->"
COMMANDS = ("council", "work", "plan", "run-plan", "review", "wiki")

SHIM = """{marker}
# /{name} — persona-roster agent OS (global shim)

Roster root on this machine: `{root}`

Follow the canonical procedure in `{root}\\.claude\\commands\\{name}.md` — read that
file FIRST and execute it exactly, with these cross-project rules (you are usually NOT
inside the roster repo):

- **TARGET project = the current working directory.** Artifacts and artifact-level
  knowledge belong HERE, following THIS project's own conventions (its CLAUDE.md /
  AGENTS.md, wiki, docs/log — probe what exists; do not force the roster's layout).
- **ROSTER = `{root}`.** All orchestration reads/writes go there: `roster.json`,
  `teams.json`, `orchestrator/**` (router, pipelines, roles, knowledge-commit),
  `wiki/decisions/`, `wiki/learnings/`, `STATE.md`, `log.md`, `index.md`.
- **Tools:** run `python "{root}\\tools\\route.py" ...` for routing and
  `python "{root}\\tools\\validate.py" --done` as the done-gate (the knowledge-commit
  log entry lands in the ROSTER log; the target project gets its own log/wiki updates
  per its conventions).
- **Personas:** spawn the user-global `<slug>-advisor` / `<slug>-operator` agents
  (installed alongside this shim). Operators do the hands-on work in the TARGET
  project; advisors never write.
"""


def is_ours(path: pathlib.Path) -> bool:
    try:
        return MARKER in path.read_text(encoding="utf-8")
    except (FileNotFoundError, UnicodeDecodeError):
        return False


def install() -> int:
    agents_dir = CLAUDE_DIR / "agents"
    commands_dir = CLAUDE_DIR / "commands"
    commands_dir.mkdir(parents=True, exist_ok=True)

    written = gen_agents.generate(agents_dir)
    print(f"Agents  -> {agents_dir}  ({len(written)} files: advisor+operator per clone)")

    skipped = []
    for name in COMMANDS:
        target = commands_dir / f"{name}.md"
        if target.exists() and not is_ours(target):
            skipped.append(target.name)
            continue
        target.write_text(SHIM.format(marker=MARKER, name=name, root=ROOT), encoding="utf-8")
    print(f"Commands-> {commands_dir}  (/{', /'.join(COMMANDS)})")
    for s in skipped:
        print(f"  SKIPPED {s}: exists and was not generated by us — resolve manually")
    print("\nDone. /work, /council, /plan, /run-plan, /review, /wiki now work from any "
          "project on this machine. Re-run after changing roster.json, teams.json, or "
          "the canonical commands. Uninstall: python tools/install_global.py --uninstall")
    return 1 if skipped else 0


def uninstall() -> int:
    removed = 0
    slugs = [c["slug"] for c in __import__("json").loads(
        (ROOT / "roster.json").read_text(encoding="utf-8")).get("clones", [])]
    agent_names = [f"{s}-{kind}.md" for s in slugs for kind in ("advisor", "operator")]
    for name in agent_names:
        p = CLAUDE_DIR / "agents" / name
        if p.exists():
            p.unlink()
            removed += 1
    for name in COMMANDS:
        p = CLAUDE_DIR / "commands" / f"{name}.md"
        if p.exists() and is_ours(p):
            p.unlink()
            removed += 1
    print(f"Removed {removed} generated file(s) from {CLAUDE_DIR}")
    return 0


def main(argv=None) -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--uninstall", action="store_true")
    a = p.parse_args(argv)
    return uninstall() if a.uninstall else install()


if __name__ == "__main__":
    sys.exit(main())
